#!/bin/bash

echo "Este teste verifica a funcionalidade básica da operação -o."
sleep 2
./argus -e "ls"
./argus -e "ls | wc"
sleep 1
echo "Output de ls | wc:"
./argus -o 2
sleep 1
echo "Output de -o 3 (n tem nada):"
./argus -o 3

