#!/bin/bash

echo "Este teste verifica se um processo com indice superior mantem a ordem no ficheiro dos indices caso acabar mais cedo."
./argus -m 15
./argus -e "ls"
./argus -e "ls | wc"
./argus -e "sleep 15" 
./argus -e "ls | wc"
sleep 3
./argus -t 3
./argus -r
echo "DEVIA SER O OUTPUT DE SLEEP:\n" 
./argus -o 3
echo "DEVIA SER O OUTPUT DE LS | WC:\n"
./argus -o 4


